name: Update README with WakaTime

on:
  schedule:
    - cron: '0 0 * * *' # Actualiza una vez al día a la medianoche UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update README
        run: |
          curl -o readme-stats.py https://raw.githubusercontent.com/anmol098/waka-readme-stats/master/github_stats.py
          python3 readme-stats.py
      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Updated WakaTime stats"
          git push
